version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o8fgoq01y3d5"
s3_prefix = "sam-app"
region = "us-east-2"
profile = "rahul"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "IdentityNameParameter=\"scraper\""
image_repositories = []
